### ISSUE TITLE
Error: "path is not defined" in onCreateWebpackConfig

### ISSUE THREAD

**Issue by daviddostal** [arnorhs/gatsby-plugin-directory-named-index#1]
When using this plugin, it throws an error signalling the `path` module is missing in `onCreateWebpackConfig` of the plugins `gatsby-node.js`.

## Error message:

```
ERROR #11330  PLUGIN

"gatsby-plugin-directory-named-index" threw an error while running the onCreateWebpackConfig lifecycle:

path is not defined

  16 |   const options = Object.assign({
  17 |     honorIndex: false,
> 18 |     exclude: [path.resolve('./src/pages'), /node_modules/],
     |               ^
  19 |     include: [path.resolve('./src'), ...(include || [])]
  20 |   }, opts);
  21 |   actions.setWebpackConfig({
  
Make sure that you don't have a typo somewhere and use valid arguments in onCreateWebpackConfig lifecycle.
Learn more about onCreateWebpackConfig here: https://www.gatsbyjs.org/docs/node-apis/#onCreateWebpackConfig

File: node_modules/gatsby-plugin-directory-named-index/gatsby-node.js:18:15
```

## Plugin options:

```js
{
    resolve: `gatsby-plugin-directory-named-index`,
    options: {
        honorIndex: true
    },
},
```

## System info:

**Node version**: v14.0.0
**Gatsby CLI version**: 2.12.45
**Gatsby version**: 2.22.15

## Possible solution:

I suspect this can be solved by just requiring the nodejs `path` module:
```js
const path = require('path')
```
It seems to work, when I tested the fix in my _projects_ `gatsby-node.js`, but I cannot test, if the fix also works directly in the _plugin_.

**I will submit a pull request with this later.**

**Comment by dougsmith1000** [comment]
@arnorhs, I see the fix in your code, but for some reason npm is installing the old version without the path requirement.

**Comment by arnorhs** [comment]
weird.. maybe I didn't publish.. closing now, since i just updated and published a new version
